# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7ffcbce4eace7b2dd2df7eeb1cd4e040"
name = "Peleman Editor"
handle = "peleman-editor"
application_url = "https://epson-informational-pulling-where.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://epson-informational-pulling-where.trycloudflare.com/auth/callback",
  "https://epson-informational-pulling-where.trycloudflare.com/auth/shopify/callback",
  "https://epson-informational-pulling-where.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
